### PR TITLE
added a step size multiplier config for page up/down

### LINKED ISSUE #1083: Add option to set page up/down multiplier
The page up/ down multiplier is set to 5, but it would be really nice if it was possible to pass in this as a config option.

### PR DESCRIPTION
**Pull request by jeffj6123**
added an additional config for #1036 to allow for the page up/down keys to be configured with a multiplier besides 5.

closes #1083

### CODE REVIEW

**Comment by leongersen** [comment]
@jeffj6123 Thanks for contributing this (and adding tests!)! I've just released noUiSlider 14.6.0, which includes this new option. I renamed it to `keyboardPageMultiplier`. I've also added a `keyboardDefaultStep` option, that allows configuration of the default `10%` stepping in a range without any configured step. Documentation is [here](http://localhost/nouislider/slider-options/#section-keyboard-support).

**Comment by bryanbuchs** [comment]
Has this made it into the latest release? I'm fidding with `keyboardDefaultStep` and `keyboardPageMultiplier` in my app and not seeing any effect.

**Comment by leongersen** [comment]
@bryanbuchs, yes, it did. The linked documentation sets the options in an example.

**Comment by jeffj6123** [comment]
hey, @leongersen it does seem like the keyboardDefaultStep size isnt working. it seems that even when I set the keyboardDefaultStep it still uses the default step size.

**Comment by jeffj6123** [comment]
so it looks like specifically its here
`
                var multiplier = options.keyboardPageMultiplier;
                var direction = isDown ? 0 : 1;
                var steps = getNextStepsForHandle(handleNumber);
                var step = steps[direction];

                // At the edge of a slider, do nothing
                if (step === null) {
                    return false;
                }

                // No step set, use the default of 10% of the sub-range
                if (step === false) {
                    step = scope_Spectrum.getDefaultStep(
                        scope_Locations[handleNumber],
                        isDown,
                        options.keyboardDefaultStep
                    );
                }
`
The step will never be false with a default step size, so the keyboard default step will only come into effect if you dont set a step config option. So as it stands it requires step to not be set for keyboardDefaultStep to be used.

**Comment by leongersen** [comment]
Yes, that's what the `keyboardDefaultStep` does. I guess the documentation needs to be clearer on that. Were you looking for a setting the set a different `step` value for keyboard interaction vs mouse/touch interaction?

**Pull request merged**
