### PR TITLE
UDM support added (CommonJS/Browserify included)

### PR DESCRIPTION
**Pull request by jesusprubio**
Implemented following the [UMD recommendations for jQuery plugins](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js), the same as @radum proposed here: https://github.com/leongersen/noUiSlider/pull/352#issuecomment-74951904

### CODE REVIEW

**Comment by radum** [comment]
:+1: from me for this one. This is a frontend plugin and this approach IMHO is much better than this one here https://github.com/leongersen/noUiSlider/pull/375

Also this change doesn't break anything just give us the possibility to import the plugin using browserify or ES6 modules.

**Comment by radum** [comment]
ping

Sorry to be a nag, but this looks good, any chance to merge it?

**Comment by jesusprubio** [comment]
Moreover the NPM guys have published some recommendations about how to make compatible a jQuery plugin. It seems we're going in the right way :)

**Comment by leongersen** [comment]
I fully intend to merge this, I simply haven't had the time to properly test it yet.

**Comment by leongersen** [comment]
This'll be in the next release

**Comment by mciparelli** [comment]
Why would I (jQuery user) want to load a plugin that does not make use of an existing jQuery (as it was already happening with this library as a standalone by checking on `window.jQuery`)? `require('jquery')` seems to call a factory everytime and return a new instance of the library. So, in Node/Browserify, I won't have an idea where this `.noUiSlider` is attached to. If I already have a jQuery object in some variable and I want to use it with many plugin-like libraries, I can't do that here because it uses some newly internally created jQuery. If someone ever recommended doing such thing I'd love to hear the reasons. I suggest simply exporting the factory when you don't have a `window.jQuery` to check on rather than not giving users the possibility to use the plugin at all.
See how jQuery does it:
```js
module.exports = global.document ?
  factory( global, true ) :
  function( w ) {
    if ( !w.document ) {
      throw new Error( "jQuery requires a window with a document" );
    }
    return factory( w );
 };
```
All it wants is a document, so it checks for a `global.document` (analog to checking for a `global.jQuery`) and returns the factory applied with such global object that contains the document. If it doesn't find it, then it just exports a factory function to call with an object that must contain a document. While I particularly don't like that much to export a different public API depending on the environment you're on, this works.
Take into consideration that while your solution _might_ (I don't really know)  work in the browser with _browserify_ it won't ever work in node, and I don't see why this environment should be left aside.

**Pull request merged**
