### PR TITLE
Feature/keyboard multiplier

### PR DESCRIPTION
**Pull request by dsasko**
First of all, thanks for writing such a useful plugin.

This PR came out of the need to differentiate regular steps from keyboard steps, but is a bit more than that.
This is particularly useful when dealing with the combination of small step sizes and big ranges.

Whats included:

- eslint
  - modified eslint rules to fit more to the current state of the script (disabled `@typescript-eslint/no-explicit-any`)
- dockerisation
  - ability to spin up the documentation with docker-compose
  - the docker container mounts the whole root folder except for the `node_modules` folder
- documentation
  - modified keyboardSupport examples and explained the `keyboardDefaultStep` a bit more
- keyboardModifier
  - added a new option that behaves just like `keyboardPageMultiplier` but for all keyboard interactions that aren't page up/down
  - added an example and explanation of the functionality to the documentation

This PR also resolves:
- #992 
- #1096

Please let me know if you would consider merging the changes and if you want me to make additional modifications.

### CODE REVIEW

**Comment by leongersen** [comment]
Hi @dsasko, thanks for your contribution. This looks good, and I like this feature and the documentation. 

I'm not so keen on merging the Docker part of the PR; I don't use Docker myself and I'd rather not maintain/support it here. If you'd remove those changes, I'll get this tested and merged.

**Comment by dsasko** [comment]
@leongersen The dockerisation was only a means to an end because I don't have php installed on my machine and I wanted to test the solution. I figured you and other future contributors could benefit from it as it would enable more people to contribute and also streamline the process a bit more.

That being said, I have removed dockerisation from the PR.

If you decide, at some point, to bring it back just let me know if you want me to create a new PR for it.

**Comment by dsasko** [comment]
@leongersen Please note this is not a breaking change as the default setting of the `keyboardModifier` is set to `1`. This will result in exactly the same behavior if the option is not defined.

**Comment by leongersen** [comment]
I've just merged this and released noUiSlider 15.3.0. Thank you, @dsasko!

I'll have a look at better documenting running the documentation locally as well (and potentially bringing in the option to run it in Docker), thanks for your feedback in that area.

**Pull request merged**
