### PR TITLE
Add event-type ("drag" or "tap") as fourth arg to "change" event callbacks.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
I think this solves https://github.com/leongersen/noUiSlider/issues/201 in a simple way. I'm happy to add tests and/or update the documentation if you'd like.

As I said in https://github.com/leongersen/noUiSlider/issues/201, I think this could go even further and modify the ``set`` event to be a ``change`` event with ``type: "set"``, but I didn't do that as it would be a breaking change.

### CODE REVIEW

**Comment by jgerigmeyer** [comment]
@leongersen Any chance of getting this merged in?

**Comment by leongersen** [comment]
Yes. I wanted to release the fixes in 8.1.0. I skipped this because I'd have to add tests + documentation, but I'll get this in very soon. Sorry for the delay!

**Comment by jgerigmeyer** [comment]
:+1:

**Comment by leongersen** [comment]
I've added a Boolean to indicate a `tap` event.

**Pull request closed without merging**
