### PR TITLE
fix(options): clone the user options to avoid mutating them

### PR DESCRIPTION
**Pull request by vvo**
Ok @leongersen this is better now.

One of the issue about the state of the project is that it's not build with something like webpack and thus you cannot use any npm dependencies and inline them.

Once we merged some good PRS, I will help you make this module commonJS compatible (in term of building)

### CODE REVIEW

**Comment by vvo** [comment]
@leongersen Updated this one, let me know what you think.

Avoiding mutating the option object is important for a library I believe. Don't touch what's not ours! :-)

**Comment by leongersen** [comment]
I'll agree to `"Don't touch what's not ours"`, but this fix pulls in a ton of code we don't need. The only time we change the original options object is [here](https://github.com/leongersen/noUiSlider/blob/master/src/js/options.js#L259), where we could change [this line](https://github.com/leongersen/noUiSlider/blob/master/src/js/options.js#L282) to `|| defaults[name]` to achieve the same effect without ever modifying the `options` object.

**Comment by vvo** [comment]
I am happy with another fix if you have one, thus we can close this PR.

**Comment by vvo** [comment]
Will you do the change?

**Comment by leongersen** [comment]
Yes, I'll fix this.

**Pull request closed without merging**
