### PR TITLE
npm: include only distribution files

### PR DESCRIPTION
**Pull request by awps**
When installed with npm, it will add all files that you see in this repository.
I've added "files" option, so only the necessary production files are installed.
Please commit this asap on npm as  it's really something that most developers will welcome.  Who don't like to keep their projects clean?

Thank you.

### CODE REVIEW

**Comment by QuentinRoy** [comment]
I think @leongersen is using .npmignore. But it is true that it could ignore a bit more.

**Comment by Smartik89** [comment]
@QuentinRoy Yes, I saw it. But again, this file ignores only `documentation/`, `*.zip`, `*.log`. 
Adding this to `package.json` will download only `distribution` folder and `LICENCE`, `README.md`, `package.json`.

That's **7** files instead of **59**.

When working on big projects that requires many  libraries and frameworks, extra files from each npm package just add unnecessary height to project.

**Comment by leongersen** [comment]
This is a good idea. I'll look at the documentation and add this in.

**Comment by leongersen** [comment]
https://github.com/npm/npm/wiki/Files-and-Ignores

**Comment by awps** [comment]
I'm doing this in all my projects. Example:
https://github.com/awps/zTip/blob/master/package.json#L31-L36

**Pull request merged**
