### PR TITLE
Added the ability to allow more than one class on elements

### LINKED ISSUE #1054: Allow to add multiple Classes in cssClasses Object
I think in Case of the grow of multiple CSS Frameworks and some of them work with functional classes (TailwindCSS) it should be able to add multiple classes to dom elements.

I tested out several syntax options and it doesnt work as a long string or even as array.

### PR DESCRIPTION
**Pull request by AntonioLeutsch**
Fixes #1054

I´ve modified the addClass function to check if there is space in the Class String so it will use the else function that will just append the classes from string to the element instead of using the add function from js.

### CODE REVIEW

**Comment by leongersen** [comment]
I'd be interested in merging this, but it would need documentation. Could you add some?

**Comment by AntonioLeutsch** [comment]
I´ve already added some text to the documentation, but if you tell me what to document in detail I will append it

**Comment by leongersen** [comment]
[Here'd](https://github.com/leongersen/noUiSlider/blob/master/documentation/more/classes.js) be good!

**Comment by AntonioLeutsch** [comment]
I´ve added a line of documentation already in the target file in my pull request :)

**Comment by leongersen** [comment]
I just merged this and released it as noUiSlider 14.2.0. Thanks for contributing!

**Pull request merged**
