### PR TITLE
Adds support more than two handles on one slider (and fixes a minor step interface bug)

### LINKED ISSUE #507: Feature request: ability to select multiple ranges
It would be nice to have the ability to select multiple ranges in the slider. Below is an example.
http://www.jqueryscript.net/slider/jQuery-Plugin-For-Multi-range-jQuery-UI-Range-Slider.html

It can be used for example in an hour schedule to select working hours.

### PR DESCRIPTION
**Pull request by michaeltandy**
Thanks for a great library - working on it has improved my meagre javascript skills!

Fixes #507 and #474 by adding support for multiple handles on the same slider.

Also, I noticed that the steps interface, as used in [the examples](http://refreshless.com/nouislider/examples/#section-keypress), didn't work quite right for nonlinear sliders where the length of a range wasn't always a multiple of the range's steps. There's a unit test to show what I mean.

### CODE REVIEW

**Comment by leongersen** [comment]
Micheal, thanks **a lot** for this contribution. I've been waaay too busy the last month. I'll try and find a moment to review this and merge it in!

**Comment by michaeltandy** [comment]
No rush, I know this merge request changes a bunch of files.

**Comment by knutole** [comment]
FYI: Will test this PR, and report back with any issues. Looks great, though, awesome job!

**Comment by leongersen** [comment]
Ok great! I'm hoping to merge this as the main feature in a new release. We'll need to have a look at the documentation as wel..

**Comment by xnakos** [comment]
Hi, guys! A couple of things concerning this pull request. I am testing this:

```
noUiSlider.create(slider, {
			start: [ 5, 10, 15 ],
			range: {
				'min': [0, 1],
				'max': [20]
			}
		});
```

You have three handles. If you take the right handle and move it to the far right and then you take the middle handle and move it to the far right, these two handles are stuck there for good. This does not seem to happen with the current (stable) range slider. The layering of handles should be looked into for multiple handles, especially when they overlap.

The other (infinitely more minor compared to the previous one) thing is that clicking on the slider (not on a handle) always "pulls" the first (left-most) slider, no matter where the click happens. Maybe it should try to "pull" the slider closest to the click, which seems to be the case for the current (stable) range slider.

Great job and much needed feature!

**Comment by knutole** [comment]
We've been testing this for a couple of weeks now, and not found any other major issues. FYI. 💯

**Comment by xnakos** [comment]
Great! Hoping for a major release! I believe that the path to solve the dead-end stacking issue is along the lines of this:

```
diff --git a/src/js/scope.js b/src/js/scope.js
index 3589bda..0dcb0a8 100644
--- a/src/js/scope.js
+++ b/src/js/scope.js
@@ -47,12 +47,14 @@
                        handle.style[options.style] = to + '%';
                }
 
-               // Force proper handle stacking
-               if ( !handle.previousSibling ) {
-                       removeClass(handle, cssClasses[17]);
-                       if ( to > 50 ) {
-                               addClass(handle, cssClasses[17]);
-                       }
+               // Handle stacking.
+               // If on the left, the stacking ordering follows the handle ordering.
+               if ( to < 50 ) {
+                       handle.childNodes[0].style.zIndex = "" + (10 + Array.prototype.indexOf.call(handle.parentNode.childNodes, handle));
+               }
+               // If on the right, the stacking ordering follows the reverse of the handle ordering.
+               else {
+                       handle.childNodes[0].style.zIndex = "" + (10 + handle.parentNode.childNodes.length - 1 - Array.prototype.indexOf.call(handle.parentNode.childNodes, handle));
                }
 
                // Update locations.
```

Pending clean-up and optimizations, of course.

**Comment by xnakos** [comment]
Or this, that feels more elegant:

```
diff --git a/src/js/scope.js b/src/js/scope.js
index 3589bda..0801492 100644
--- a/src/js/scope.js
+++ b/src/js/scope.js
@@ -47,13 +47,10 @@
                        handle.style[options.style] = to + '%';
                }
 
-               // Force proper handle stacking
-               if ( !handle.previousSibling ) {
-                       removeClass(handle, cssClasses[17]);
-                       if ( to > 50 ) {
-                               addClass(handle, cssClasses[17]);
-                       }
-               }
+               // Handle stacking by re-ordering the DOM elements. Every handle
+               // that is moved goes to the top of the stack (so that the movement
+               // can be reverted).
+               handle.parentNode.appendChild(handle);
 
                // Update locations.
                scope_Locations[trigger] = to;
```

**Comment by michaeltandy** [comment]
I'm busy this weekend (attending Reading Beer and Cider Festival) but I
will try to make this change shortly.

Is this change something that can be unit tested easily?

**Comment by leongersen** [comment]
These things are really tricky to test, esp. cross browser. I think it could be done by firing a click event and seeing which handle receives it. I like @xnakos' last solution, but I'm not sure how it works with the `connect` option.

**Comment by xnakos** [comment]
DOM re-ordering should be avoided, I think, even if `connect` works (I came across your great slider just recently, so I have not played around much). I am not sure whether the take-and-append action above happens at every movement, that is even if the handle is already the last child (from a previous movement). This could be checked before the append, of course, but maybe other solutions should be looked into. I have one in mind, which combines stuff from the two proposed methods above. It features a stack where every moved handle moves to the top of all handles, but the stack is implemented with z-indices. Imagine that you have 5 handles and at some point your handles have 10, 11, 12, 13, 14 z-index values. When the code section above is reached (movement has occurred), the code checks whether the z-index of the handle is 10 + total_number_of_handles - 1. If that is the case, then there is nothing to happen. If we moved the handle with 14 z-index, we are already at the top of the stack. If that is not the case, e.g. we have moved the handle with 12 z-index, then what happens is this. We mark 12 as the previous value. We make the handle z-index value equal to 10 + total_number_of_handles, e.g. 15 in our case. And we iterate over all handles and we decrease by 1 all z-indices that are above 12 (previous z-index value, no need to change handles under that). What do you think?

**Comment by leongersen** [comment]
The reposition happens only on the end of a movement, so it isn't to bad. Two assumptions that I'd have to measure to confirm: 1) The browser is smart enough not to move the element in the DOM if it doesn't have to, 2) it we change the z-indices of all handles, all of these will need to be visually re-ordered, although I guess the browser would -again- be able to determine wether something changed or not.

**Comment by xnakos** [comment]
> The browser is smart enough not to move the element in the DOM if it doesn't have to
Even if the browser is not that smart (let us take that for granted), nextSibling could be checked, and not do anything if the value is `null`, which would mean that the element is already at the end of its DOM level.
> it we change the z-indices of all handles, all of these will need to be visually re-ordered, although I guess the browser would -again- be able to determine wether something changed or not
Since the first version I proposed works fine visually, given the functionality it was meant to have, the z-index change is handled by the browser without anything else needed, exactly like `noUi-stacking` class updates the stacking of the handles when the class is applied.

Something that could be taken into consideration. Would something like that be needed?

multiple-handle-connect

Pending some rounding. Since `connect` is disabled for more than two handles, maybe an extension as an array could be used for that case. But this would not be possible if re-ordering of the DOM was used. This would only be possible if the `noUi-origin` divs were drawn at the fixed and final order of the handles.

**Comment by xnakos** [comment]
@michaeltandy Could you please review the following? It is a branch of `michaeltandy:merge-back-with-updates`. 

https://github.com/xnakos/noUiSlider/tree/fix-move-the-correct-handle

This is supposed to support tapping on the slider and moving the correct handle, even if many handles are on exactly the same position. If you think it is fine, you could pull it in `michaeltandy:merge-back-with-updates`.

**Comment by xnakos** [comment]
A preliminary patch (just a bit rough but not intrusive) for multiple handle connect (with default coloring) is this:

```
diff --git a/src/js/options.js b/src/js/options.js
index 8c05277..748a282 100644
--- a/src/js/options.js
+++ b/src/js/options.js
@@ -103,8 +103,8 @@
                        parsed.connect = 3;
                } else if ( entry === false ) {
                        parsed.connect = 0;
-               } else if (parsed.handles > 2) {
-                       throw new Error("noUiSlider: 'connect' option does not support sliders with more than two handles.");
+               } else if ( entry.constructor === Array && entry.length == parsed.handles + 1 ) {
+                       parsed.connect = entry;
                } else {
                        throw new Error("noUiSlider: 'connect' option doesn't match handle count.");
                }
diff --git a/src/js/structure.js b/src/js/structure.js
index 4d10046..d753314 100644
--- a/src/js/structure.js
+++ b/src/js/structure.js
@@ -72,10 +72,32 @@
        // Add the proper connection classes.
        function addConnection ( connect, target, handles ) {
 
+               var tmpConnect = connect;
+
                // Apply the required connection classes to the elements
                // that need them. Some classes are made up for several
                // segments listed in the class list, to allow easy
                // renaming and provide a minor compression benefit.
+               if (tmpConnect.constructor === Array) {
+                       var hasConnection = tmpConnect.shift();
+                       if (hasConnection === false) {
+                               addClass(target, options.cssClasses.background);
+                       }
+                       else {
+                               addClass(target, options.cssClasses.connect);
+                       }
+                       handles.forEach(function(handle) {
+                               hasConnection = tmpConnect.shift();
+                               if (hasConnection === false) {
+                                       addClass(handle, options.cssClasses.background);
+                               }
+                               else {
+                                       addClass(handle, options.cssClasses.connect);
+                               }
+                       });
+                       return;
+               }
+
                switch ( connect ) {
                        case 1: addClass(target, options.cssClasses.connect);
                                        addClass(handles[0], options.cssClasses.background);
```

Using this:

```
var slider = document.getElementById('slider');
	noUiSlider.create(slider, {
		start: [5, 15, 20, 30],
		step: 1,
		connect: [true, false, true, false, true],
		range: {
			min: [0],
			max: [40]
		}
	});
```

The result is this:

multiple-handle-connect

I will be checking it some more and finally pushing it at some branch. I am in a bit of a hurry to implement some stuff because of a beta stage of a project I am working on. Any feedback would be nice, since I am fond of fish swimming upstream.

**Comment by leongersen** [comment]
Sorry for my lack of response lately. The proposed API for the `connect` option looks *really* good, completely in line with the other options. 

If we do switch to using separate elements for connects (see my [other comment](https://github.com/michaeltandy/noUiSlider/pull/1#issuecomment-217367193)), we could perhaps re-open #439 and implement all positioning as transforms, instead `left`/`right`/`top`/`bottom`. That's a change for another day though, let's merge this first.

My final concern is the documentation, we'll need to thoroughly update the API changes made in this feature.

**Comment by xnakos** [comment]
Separate elements for connects (that are not linked to the handles that separate them - apart from depending on the handles' transforms (although I am not familiar with transforms, I think I feel what this will accomplish)) seems like a great idea. Even DOM re-ordering for handles, if that would be considered, would not break connect, if connects were separate. It would also be nice if the layout of connects did not even depend on the order of them appearing in the DOM. Imagine that you have a slider perfectly divided by two handles. The first connect (or no-connect) would ideally take 33.3% and not 100% (also needing the second connect to be drawn above it and take 66.6% and so on), the second connect would take 33.3%, and so on (it is funny when "so on" refers to just one remaining element :stuck_out_tongue: ). Although this would require two transforms for connects, when moving the handle, i.e. the right side of the left connect and the left side of the right connect, instead of one transform when layering is used. Just complementary thoughts for note-keeping.

I hope that keeping track of changes and examples will make documenting the API changes better. Or, maybe, that is just my excuse for spamming you.

So, to sum up the connect changes, they were based on the current implementation of yours, changing nothing. They should be fully backwards compatible and they break no tests. Also, if you use:

```
	var slider1 = document.getElementById('slider1');
	noUiSlider.create(slider1, {
		start: [5, 8],
		step: 1,
		connect: true,
		range: {
			min: [0],
			max: [10]
		}
	});
	var slider2 = document.getElementById('slider2');
	noUiSlider.create(slider2, {
		start: [5, 8],
		connect: [false, true, false],
		step: 1,
		range: {
			min: [0],
			max: [10]
		}
	});
```

The two sliders have exactly the same DOM. Maybe with just a bit of refactoring the ENUM {0,1,2,3} you use could go away from the `addConnection` function and, after parsing the options, supply to the function the equivalent array for the current options ([false, true, false] for true, [false, false] or [false, false, false] for false, [false, true] for 'upper', [true, false] for 'lower', depending on the handle count).

**Comment by leongersen** [comment]
FYI: I've (finally - my bad) started on this, implementing the connecting option first, then documentation.

**Comment by leongersen** [comment]
FYI: I'm working on this now. I'm implementing `connect` for multiple handles, too.

Issues I've encountered so far:
- The `drag` behaviour doesn't work
- Function complexity has gone up, particularly in the events sections. I'm refactoring here and there.

**Comment by leongersen** [comment]
I've released noUiSlider 9.0.0 yesterday, which includes this feature! I know it has been a long road, but thanks for your contributions @michaeltandy & @xnakos.

**Comment by michaeltandy** [comment]
That's great! Thanks for the work you do maintaining this project!

**Comment by xnakos** [comment]
@leongersen @michaeltandy Thank you for your work, guys!

**Comment by zackster** [comment]
Just checking, there's no way to dynamically add or remove a handle, is there?

**Comment by leongersen** [comment]
@zackster: rebuilding is the way to go.

**Pull request merged**
