### PR TITLE
Inverted Connects for unconstrained behavior

### PR DESCRIPTION
**Pull request by 5andr0**
Here's an implementation idea for [feature request #1262](https://github.com/leongersen/noUiSlider/issues/1262#issuecomment-1861327398)
I had a similar request for a slider which selects a yearly season range, which also had to cover overlaps over December-January.
The only way to achieve this was to destroy and recreate the slider with inverted connects when an overlap happens, but that destroyed the slider drag focus aswell, so you can never get the sliders past each other.

So I had to write my own patch adding a new behavior `"invert-connects"` which can be used like that:
```js
noUiSlider.create(document.getElementById('slider'), {
        start: [1, 12],
        connect: true,
        range: {
            'min': 1,
            'max': 12
        },
        behaviour: "unconstrained-invert-connects-drag",
        step: 1,
    });
```

I also made it possible to manually control inverting connects with the added API `invertConnects` or updating any connects options via `updateOptions`.

This patch is IE9 compatible!

### CODE REVIEW

**Comment by 5andr0** [comment]
@leongersen Implemented the changes into _nouislider.ts_ and added documentation.
Tests were successful with _nouislider.min.js_ generated by `npm run build`.
Only tested the documentation in an html environment, not the full php docs site.
I also left a donation, thanks for the project!

**Comment by leongersen** [comment]
Thanks for your PR, as well as your sponsorship, I appreciate it. 

I'm having a spin at testing this right now. An issue I'm running into is that [this logic](https://github.com/leongersen/noUiSlider/pull/1272/files#diff-c1296e0eb5b735b3f8e23a78b0a0c47be5bf3f067a345d29f9c56eda9f259cebR2678) does not fully account for more than two handles. 

You'll see what I mean if you set the start values in the added documentation to `start: [20*60, 8*60, 10*60, 16*60]` (as an example). 

image

I'm having a look to see if I can get that in.

**Comment by 5andr0** [comment]
> Thanks for your PR, as well as your sponsorship, I appreciate it.
> 
> I'm having a spin at testing this right now. An issue I'm running into is that [this logic](https://github.com/leongersen/noUiSlider/pull/1272/files#diff-c1296e0eb5b735b3f8e23a78b0a0c47be5bf3f067a345d29f9c56eda9f259cebR2678) does not fully account for more than two handles.
> 
> You'll see what I mean if you set the start values in the added documentation to `start: [20*60, 8*60, 10*60, 16*60]` (as an example).
> 
> image
> 
> I'm having a look to see if I can get that in.

Yea, I was thinking about it supporting more than 2 handles, but came to the conclusion that it really doesn't make sense to use this outside of 2 handles. Couldn't think of a usecase. If someone really needs two ranges overlapping from end to start, they can just implement two sliders for it. Maybe you can add a commit to limit it to 2 handles or just a note in the documentation.

**Comment by leongersen** [comment]
I came to the same conclusion; this is a nice feature and there is not much of a use case of trying to implement this for sliders with more than two handles.

I'm making some changes:
- Document that `connect` can be updated
- Bypass the full update logic when only the connects need to update
- Throw an error if `invertConnects` is used on sliders that do not have to handles
- Fix eslint

**Comment by 5andr0** [comment]
> I came to the same conclusion; this is a nice feature and there is not much of a use case of trying to implement this for sliders with more than two handles.
> 
> I'm making some changes:
> 
> * Document that `connect` can be updated
> * Bypass the full update logic when only the connects need to update
> * Throw an error if `invertConnects` is used on sliders that do not have to handles
> * Fix eslint

Changes sound good! Thanks so much for your help to implement this 🤩

**Comment by leongersen** [comment]
I've merged this and released noUiSlider 15.8.0. Thank you for contributing!

https://refreshless.com/nouislider/behaviour-option/#section-invert-connects

**Pull request merged**
