### PR TITLE
Create `drag` event for when a connect is being dragged

### LINKED ISSUE #887: drag event
it doesn't seem there is a drag event - only an update or slide event.

assuming a connect bar between two handles, if one moves the connect bar, two events are triggered - one for each handle.

is there a way - or could one be implemented - to fire a "connect" event, once, with the new values and perhaps a handle of -1?

the reason? I am using noUISlider as zoom/pan controls on a d3 chart. altering the connect/start range is the equivalent of zoom. dragging the connect bar is the equivalent of pan. right now, the events that are triggered don't let me distinguish between the two.

s.

### PR DESCRIPTION
**Pull request by IRHM**
There is no event for when a user drags a connect between two starts, this PR creates one named `drag`.

It adds these lines:

```
// If target is a connect, then fire drag event
if (data.target != undefined && hasClass(data.target, options.cssClasses.connect)) {
    fireEvent("drag", data.handleNumbers[0]);
}
```

to the `eventMove()` function. I'm not very familiar with this code base, so I have no idea if this is a good spot to put this (could be a little less performant, since it is checking if the target is a connect on all move events. Don't know how big of an impact this would be though).

Currently it just returns the first handle number (`data.handleNumbers[0]`) and to access both values of the starts connected together you'd have to do something like this:

```
slider.noUiSlider.on('drag', function (values, handle) {
    // (handle) for 1st value
    // (handle +1) for second value
    console.log(values[handle], values[handle + 1]);
});
```

I have added this event to the documentation. The demo slider now features a connection between the two handles that were already there and the behaviour is set to 'drag-tap', so that people can test the drag event. I have also modified the padding a little on the `.example` and `.view-more` classes so that the `events fire order` list can be on one line for desktop users.

Closes #887

### CODE REVIEW

**Comment by IRHM** [comment]
@leongersen What do you think about where the `drag` event is being fired? I feel like there is a much better place it could go that I am unaware of.

**Comment by leongersen** [comment]
Thank you for this PR. I like these changes, and I think this additional event makes sense. Regarding where it is fired: I'd move it into the `moveHandles` function that is called from the `eventMove` function where it is placed now. This would allow for a check  on `state` there, so the event only fires if anything actually changed.

Regarding the check on whether the element is a connect, I'd like to see this added as a property to `EventData` and passed from the start [here](https://github.com/leongersen/noUiSlider/blob/5a194089a1f04189a5014ee7416f427c5f7971c1/src/nouislider.ts#L2339). 

The documentation should also mention which `handleNumber` is given as the argument to the `drag` event.

**Comment by IRHM** [comment]
@leongersen I'll work on that, thanks for the feedback!

**Comment by IRHM** [comment]
@leongersen Does that all look good now?

**Comment by leongersen** [comment]
Yes, looks great! I've just merged this and release noUiSlider 15.1.0. Thanks for contributing!

**Pull request merged**
