### PR TITLE
fix(constants): only compute constants when needed

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by leongersen** [comment]
Might as well move `actions` into `scope.js`, as it isn't used more globally than that.

**Comment by vvo** [comment]
Do you mean inside closure()?

**Comment by leongersen** [comment]
Yes. We could do `var actions = getActions()`.

**Comment by vvo** [comment]
WFM, will update

**Comment by vvo** [comment]
Not sure what you really wanted, I could just move everything grom constants in scope_start I believe since it's where they are really used and there's no obvious performance gain as trying to make them constants. Those will already be optimized as "constants" by V8 somehow because they are never re-assigned.

Let me know if you want to move it all to scope_start.js. Might be easier to understand.

**Comment by vvo** [comment]
updated

**Comment by vvo** [comment]
wait I messed up somewhere

**Comment by vvo** [comment]
ok we are good :)

**Comment by vvo** [comment]
Bump @leongersen

**Comment by leongersen** [comment]
I've got a weekend off -for the first time since forever :smirk: - starting tomorrow. I intend to merge open pull requests and fix/triage the open issues. Sorry for the wait.

**Comment by vvo** [comment]
Nice!

**Pull request merged**
