### PR TITLE
Implement drag all when more than two handles are configured

### PR DESCRIPTION
**Pull request by sam9291**
This PR fixes the issue #756 

I've also updated the documentation accordingly, providing an example of the result.

sample

### CODE REVIEW

**Comment by leongersen** [comment]
This looks good. I'll give it a test (and add a unit test or two). Nothing about this pull request would break other features, so I think merging it will be easy. Sorry for not responding earlier; I've been travelling for a while.

**Comment by leongersen** [comment]
I'm closing this PR as it has become stale. I'd be willing to accept a new PR on this feature (the code provided here should be easy to port), if it was made part of the current `behaviour` flag and tests + documentation were added.

**Comment by fuhquan** [comment]
Is this still implementable or adaptable for the latest release? This would solve the last open issue I have with my slider configuration.

**Comment by leongersen** [comment]
Yes, the changes in this PR should be straightforward to port to the current state of the code.

**Comment by reshmiram** [comment]
Hi,
Will this feature be implemented in the future? This will be very useful for the application I am working on.
Thanks

**Comment by leongersen** [comment]
@reshmiram Not by me, but if you are willing to submit a PR for this feature I'd be interested. The submission here would need to be updated and have unit tests added.

**Comment by reshmiram** [comment]
Thank you for responding quickly. I will give that a go.

**Comment by leongersen** [comment]
This feature is now available in noUiSlider 15.4.0. Thank you for contributing!

**Pull request closed without merging**
