### PR TITLE
feature: join overlapping tooltips with direction and orientation support

### PR DESCRIPTION
**Pull request by omuryildirim**
Issue #1032

[This pull request](https://github.com/leongersen/noUiSlider/pull/1033) was closed due to missing direction and orientation support.

### CODE REVIEW

**Comment by leongersen** [comment]
I'm really glad you continued working on this! I should have time to integrate this sometime this week.

**Comment by leongersen** [comment]
I'm working on testing this; so far I'm running into only the first two overlapping handles getting merged. I'll try to see if I can adapt the logic for that case. 

image

**Comment by omuryildirim** [comment]
actually it's suppose to work with two overlapping handles. I will take a look tomorrow for merging three overlapping handles.

**Comment by omuryildirim** [comment]
just updated how joint tooltips works so that it will support joint of all overlapping tooltips

**Comment by byNiko** [comment]
Looking forward to this merge.  Any way I can help?

**Comment by leongersen** [comment]
@omuryildirim @byNiko I like this feature, but this PR adds a lot of code to the library without any covering tests. The general logic can be implemented using the event system by exposing some minor slider internals. I'll add an example to the documentation later today implementing this feature.

**Comment by leongersen** [comment]
The documentation now has an [example for merging overlapping tooltips](https://refreshless.com/nouislider/examples/#section-merging-tooltips)!

@omuryildirim In the example I went with a somewhat different approach for deciding if tooltips overlap; instead of checking the actual tooltip dimensions, I've simply configured a threshold after which tooltips should be merging. This has the added benefits of causing a lot less layout thrashing. Thanks for your suggestions and contributions on this issue! I've add you as a contributor on 3792a7b5a478133550022d465223d2181ec0a55a.

image

**Comment by fredyagomez** [comment]
@leongersen @omuryildirim  thanks guys for working on this. I did notice that after the `mergeTooltips` function runs, I am not able to drag the slider by grabbing the tooltip anymore. A feature that was present before, any quick fix you can think on?.

**Comment by fredyagomez** [comment]
@leongersen @omuryildirim without having too much time to look through the implementation, I noticed this code makes all the events like mouse down and mouse drag to be removed from the tooltip.

```
// Move tooltips into the origin element. The default stylesheet handles this.
    tooltips.forEach(function (tooltip, index) {
        if (tooltip) {
            origins[index].appendChild(tooltip);
        }
    });
```

If there were another way to move the tooltips to the origin without losing the events. Let me know if something comes to your mind.

**Comment by leongersen** [comment]
@fredyagomez You can increase the handle touch area to overlap the tooltips, like so:

```
.noUi-handle {
    position: relative;
}

.noUi-touch-area {
    position: absolute;
    top: -50px;
    bottom: 0;
    right: -5px;
    left: -5px;
    z-index: 1;
    width: auto;
    height: auto;
}
```

**Pull request closed without merging**
