### PR TITLE
copied changes from #841-modified drag behaviour to include drag all …

### PR DESCRIPTION
**Pull request by reshmiram**
…handles; changed check for fixed-drag behaviour; added testDragAllHandles

### CODE REVIEW

**Comment by reshmiram** [comment]
Hi @leongersen,
Happy New Year!!

I would appreciate it if you could take a look at the changes.
Thanks.

**Comment by leongersen** [comment]
@reshmiram Thanks for submitting these changes. Could you add a unit test for this feature?

**Comment by reshmiram** [comment]
@leongersen There are no unit tests in the project currently for any of the "drag" events, so it might be difficult for me to do them without a reference.

**Comment by leongersen** [comment]
This feature is now available in noUiSlider 15.4.0. Thank you for contributing!

**Pull request closed without merging**
