### PR TITLE
Firefox sticky handlers bug workaround #543

### PR DESCRIPTION
**Pull request by Nihilivin**
Simple workaround that emit the end event as soon as document.mouseout is emitted. Seems to work find on Chrome && Firefox, not tested on others.

### CODE REVIEW

**Comment by leongersen** [comment]
This is a good fix, but the pull has some issues. It forgets to unbind the `mouseleave` event in end. 

I'm doing this now:

```
var outEvent = attach("mouseout", d, documentLeave, { handles: data.handles });
d.noUiListeners = moveEvent.concat(endEvent, outEvent);
```

**Comment by Nihilivin** [comment]
Ok, so, do you need me to do anything?

**Comment by leongersen** [comment]
Nope, I got it in :)

**Comment by leongersen** [comment]
Thanks for the hints here, it should now be fixed!

**Comment by Nihilivin** [comment]
GG well played ;)

**Pull request closed without merging**
