### PR TITLE
Include non-minified css in distribute folder

### PR DESCRIPTION
**Pull request by tnajdek**

### CODE REVIEW

**Comment by leongersen** [comment]
ryan reynolds but why - imgur

**Comment by leongersen** [comment]
In all seriousness, why would you want this?

**Comment by tnajdek** [comment]
In short: because you don't know how your package is used by others.

One example is a scenario where someone uses your package as a part of a build process where files are concatenated together and sourcemaps are created during the development. Perhaps someone wants to publish a development version with all source code readable. In either case it's nice to have the unmangled css file available.

Also I believe it's quite common to include both minified and unminified source as part of your distribution, few completely random examples: [bootstrap](https://github.com/twbs/bootstrap/tree/master/dist), [chosen](https://github.com/harvesthq/chosen/releases), [select2](https://github.com/select2/select2/tree/master/dist/css), [bootstrap-slider](https://github.com/seiyria/bootstrap-slider/tree/master/dist/css).

**Comment by leongersen** [comment]
Good points, merged!

**Pull request merged**
