### PR TITLE
Fix support for using npm and libraries like browserify

### PR DESCRIPTION
**Pull request by lennerd**
I was not able to setup the current `master` branch from github with npm and browserify.

Beside the fact, that the intro file is still referencing the jQuery library, the `package.json` file also point to an old distribution file not present any longer.

This PR fixes both bugs and add a missing license to the `package.json` file.

### CODE REVIEW

**Comment by leongersen** [comment]
Does this address the [concerns](https://github.com/leongersen/noUiSlider/pull/417#issuecomment-117157583) @mciparelli had?

**Comment by lennerd** [comment]
I think the comment in #417 mentioned the implementation of dependency to jQuery.

As jQuery ist not part of this library any longer, this is not really fixed here, rather I removed deprecated code, which probaly was left in, when the jQuery dependency was removed. With this PR @mciparelli should be able to use noUiSlider with browsery.

**Comment by mciparelli** [comment]
If jQuery now depends on the user then I think this commit is good! =)

**Comment by leongersen** [comment]
Thanks, @lennerd, for fixing this. I've merged the changes and released them as 8.0.2.

**Pull request merged**
